name: Latest GitHub activities workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest GitHub activities 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://github.com/michaelmsonne.atom'
          max_post_count: '25'
          comment_tag_name: 'LATESTACTIVITYGITHUB'
          remove_duplicates: 'true'
